package claymod.lib;

import net.minecraft.item.Item;
import claymod.items.tools.CmClayPickaxe;

public class ClayColors {
	
	//DEFAULT COLORS
	public static final int BLACKCLAYSTICK_COLOR_DEFAULT = 0x191919;
	public static final int REDCLAYSTICK_COLOR_DEFAULT = 0x993333;
	public static final int GREENCLAYSTICK_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNCLAYSTICK_COLOR_DEFAULT = 0x664C33;
	public static final int BLUECLAYSTICK_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLECLAYSTICK_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANCLAYSTICK_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYCLAYSTICK_COLOR_DEFAULT = 0x999999;
	public static final int GRAYCLAYSTICK_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKCLAYSTICK_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMECLAYSTICK_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWCLAYSTICK_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUECLAYSTICK_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTACLAYSTICK_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGECLAYSTICK_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITECLAYSTICK_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDCLAYSTICK_COLOR_DEFAULT = 0x957D5A;

	
	public static final int BLACKPICKAXE_COLOR_DEFAULT = 0x191919;
	public static final int REDPICKAXE_COLOR_DEFAULT = 0x993333;
	public static final int GREENPICKAXE_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNPICKAXE_COLOR_DEFAULT = 0x664C33;
	public static final int BLUEPICKAXE_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLEPICKAXE_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANPICKAXE_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYPICKAXE_COLOR_DEFAULT = 0x999999;
	public static final int GRAYPICKAXE_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKPICKAXE_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMEPICKAXE_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWPICKAXE_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUEPICKAXE_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTAPICKAXE_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGEPICKAXE_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITEPICKAXE_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDPICKAXE_COLOR_DEFAULT = 0x957D5A;

	public static final int BLACKAXE_COLOR_DEFAULT = 0x191919;
	public static final int REDAXE_COLOR_DEFAULT = 0x993333;
	public static final int GREENAXE_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNAXE_COLOR_DEFAULT = 0x664C33;
	public static final int BLUEAXE_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLEAXE_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANAXE_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYAXE_COLOR_DEFAULT = 0x999999;
	public static final int GRAYAXE_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKAXE_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMEAXE_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWAXE_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUEAXE_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTAAXE_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGEAXE_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITEAXE_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDAXE_COLOR_DEFAULT = 0x957D5A;

	public static final int BLACKHOE_COLOR_DEFAULT = 0x191919;
	public static final int REDHOE_COLOR_DEFAULT = 0x993333;
	public static final int GREENHOE_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNHOE_COLOR_DEFAULT = 0x664C33;
	public static final int BLUEHOE_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLEHOE_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANHOE_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYHOE_COLOR_DEFAULT = 0x999999;
	public static final int GRAYHOE_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKHOE_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMEHOE_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWHOE_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUEHOE_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTAHOE_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGEHOE_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITEHOE_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDHOE_COLOR_DEFAULT = 0x957D5A;

	public static final int BLACKSHOVEL_COLOR_DEFAULT = 0x191919;
	public static final int REDSHOVEL_COLOR_DEFAULT = 0x993333;
	public static final int GREENSHOVEL_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNSHOVEL_COLOR_DEFAULT = 0x664C33;
	public static final int BLUESHOVEL_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLESHOVEL_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANSHOVEL_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYSHOVEL_COLOR_DEFAULT = 0x999999;
	public static final int GRAYSHOVEL_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKSHOVEL_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMESHOVEL_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWSHOVEL_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUESHOVEL_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTASHOVEL_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGESHOVEL_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITESHOVEL_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDSHOVEL_COLOR_DEFAULT = 0x957D5A;

	public static final int BLACKSWORD_COLOR_DEFAULT = 0x191919;
	public static final int REDSWORD_COLOR_DEFAULT = 0x993333;
	public static final int GREENSWORD_COLOR_DEFAULT = 0x667F33;
	public static final int BROWNSWORD_COLOR_DEFAULT = 0x664C33;
	public static final int BLUESWORD_COLOR_DEFAULT = 0x334CB2;
	public static final int PURPLESWORD_COLOR_DEFAULT = 0x7F3FB2;
	public static final int CYANSWORD_COLOR_DEFAULT = 0x4C7F99;
	public static final int LIGHTGRAYSWORD_COLOR_DEFAULT = 0x999999;
	public static final int GRAYSWORD_COLOR_DEFAULT = 0x4C4C4C;
	public static final int PINKSWORD_COLOR_DEFAULT = 0xF27FA5;
	public static final int LIMESWORD_COLOR_DEFAULT = 0x7FCC19;
	public static final int YELLOWSWORD_COLOR_DEFAULT = 0xE5E533;
	public static final int LIGHTBLUESWORD_COLOR_DEFAULT = 0x6699D8;
	public static final int MAGENTASWORD_COLOR_DEFAULT = 0xB24CD8;
	public static final int ORANGESWORD_COLOR_DEFAULT = 0xD87F33;
	public static final int WHITESWORD_COLOR_DEFAULT = 0xFFFFFF;
	public static final int HARDSWORD_COLOR_DEFAULT = 0x957D5A;

	//COLORS
	public static int BLACKCLAYSTICK_COLOR = 0x191919;
	public static int REDCLAYSTICK_COLOR = 0x993333;
	public static int GREENCLAYSTICK_COLOR = 0x667F33;
	public static int BROWNCLAYSTICK_COLOR = 0x664C33;
	public static int BLUECLAYSTICK_COLOR = 0x334CB2;
	public static int PURPLECLAYSTICK_COLOR = 0x7F3FB2;
	public static int CYANCLAYSTICK_COLOR = 0x4C7F99;
	public static int LIGHTGRAYCLAYSTICK_COLOR = 0x999999;
	public static int GRAYCLAYSTICK_COLOR = 0x4C4C4C;
	public static int PINKCLAYSTICK_COLOR = 0xF27FA5;
	public static int LIMECLAYSTICK_COLOR = 0x7FCC19;
	public static int YELLOWCLAYSTICK_COLOR = 0xE5E533;
	public static int LIGHTBLUECLAYSTICK_COLOR = 0x6699D8;
	public static int MAGENTACLAYSTICK_COLOR = 0xB24CD8;
	public static int ORANGECLAYSTICK_COLOR = 0xD87F33;
	public static int WHITECLAYSTICK_COLOR = 0xFFFFFF;
	public static int HARDCLAYSTICK_COLOR = 0x957D5A;

	public static int BLACKPICKAXE_COLOR = 0x191919;
	public static int REDPICKAXE_COLOR = 0x993333;
	public static int GREENPICKAXE_COLOR = 0x667F33;
	public static int BROWNPICKAXE_COLOR = 0x664C33;
	public static int BLUEPICKAXE_COLOR = 0x334CB2;
	public static int PURPLEPICKAXE_COLOR = 0x7F3FB2;
	public static int CYANPICKAXE_COLOR = 0x4C7F99;
	public static int LIGHTGRAYPICKAXE_COLOR = 0x999999;
	public static int GRAYPICKAXE_COLOR = 0x4C4C4C;
	public static int PINKPICKAXE_COLOR = 0xF27FA5;
	public static int LIMEPICKAXE_COLOR = 0x7FCC19;
	public static int YELLOWPICKAXE_COLOR = 0xE5E533;
	public static int LIGHTBLUEPICKAXE_COLOR = 0x6699D8;
	public static int MAGENTAPICKAXE_COLOR = 0xB24CD8;
	public static int ORANGEPICKAXE_COLOR = 0xD87F33;
	public static int WHITEPICKAXE_COLOR = 0xFFFFFF;
	public static int HARDPICKAXE_COLOR = 0x957D5A;

	public static int BLACKAXE_COLOR = 0x191919;
	public static int REDAXE_COLOR = 0x993333;
	public static int GREENAXE_COLOR = 0x667F33;
	public static int BROWNAXE_COLOR = 0x664C33;
	public static int BLUEAXE_COLOR = 0x334CB2;
	public static int PURPLEAXE_COLOR = 0x7F3FB2;
	public static int CYANAXE_COLOR = 0x4C7F99;
	public static int LIGHTGRAYAXE_COLOR = 0x999999;
	public static int GRAYAXE_COLOR = 0x4C4C4C;
	public static int PINKAXE_COLOR = 0xF27FA5;
	public static int LIMEAXE_COLOR = 0x7FCC19;
	public static int YELLOWAXE_COLOR = 0xE5E533;
	public static int LIGHTBLUEAXE_COLOR = 0x6699D8;
	public static int MAGENTAAXE_COLOR = 0xB24CD8;
	public static int ORANGEAXE_COLOR = 0xD87F33;
	public static int WHITEAXE_COLOR = 0xFFFFFF;
	public static int HARDAXE_COLOR = 0x957D5A;

	public static int BLACKHOE_COLOR = 0x191919;
	public static int REDHOE_COLOR = 0x993333;
	public static int GREENHOE_COLOR = 0x667F33;
	public static int BROWNHOE_COLOR = 0x664C33;
	public static int BLUEHOE_COLOR = 0x334CB2;
	public static int PURPLEHOE_COLOR = 0x7F3FB2;
	public static int CYANHOE_COLOR = 0x4C7F99;
	public static int LIGHTGRAYHOE_COLOR = 0x999999;
	public static int GRAYHOE_COLOR = 0x4C4C4C;
	public static int PINKHOE_COLOR = 0xF27FA5;
	public static int LIMEHOE_COLOR = 0x7FCC19;
	public static int YELLOWHOE_COLOR = 0xE5E533;
	public static int LIGHTBLUEHOE_COLOR = 0x6699D8;
	public static int MAGENTAHOE_COLOR = 0xB24CD8;
	public static int ORANGEHOE_COLOR = 0xD87F33;
	public static int WHITEHOE_COLOR = 0xFFFFFF;
	public static int HARDHOE_COLOR = 0x957D5A;

	public static int BLACKSHOVEL_COLOR = 0x191919;
	public static int REDSHOVEL_COLOR = 0x993333;
	public static int GREENSHOVEL_COLOR = 0x667F33;
	public static int BROWNSHOVEL_COLOR = 0x664C33;
	public static int BLUESHOVEL_COLOR = 0x334CB2;
	public static int PURPLESHOVEL_COLOR = 0x7F3FB2;
	public static int CYANSHOVEL_COLOR = 0x4C7F99;
	public static int LIGHTGRAYSHOVEL_COLOR = 0x999999;
	public static int GRAYSHOVEL_COLOR = 0x4C4C4C;
	public static int PINKSHOVEL_COLOR = 0xF27FA5;
	public static int LIMESHOVEL_COLOR = 0x7FCC19;
	public static int YELLOWSHOVEL_COLOR = 0xE5E533;
	public static int LIGHTBLUESHOVEL_COLOR = 0x6699D8;
	public static int MAGENTASHOVEL_COLOR = 0xB24CD8;
	public static int ORANGESHOVEL_COLOR = 0xD87F33;
	public static int WHITESHOVEL_COLOR = 0xFFFFFF;
	public static int HARDSHOVEL_COLOR = 0x957D5A;

	public static int BLACKSWORD_COLOR = 0x191919;
	public static int REDSWORD_COLOR = 0x993333;
	public static int GREENSWORD_COLOR = 0x667F33;
	public static int BROWNSWORD_COLOR = 0x664C33;
	public static int BLUESWORD_COLOR = 0x334CB2;
	public static int PURPLESWORD_COLOR = 0x7F3FB2;
	public static int CYANSWORD_COLOR = 0x4C7F99;
	public static int LIGHTGRAYSWORD_COLOR = 0x999999;
	public static int GRAYSWORD_COLOR = 0x4C4C4C;
	public static int PINKSWORD_COLOR = 0xF27FA5;
	public static int LIMESWORD_COLOR = 0x7FCC19;
	public static int YELLOWSWORD_COLOR = 0xE5E533;
	public static int LIGHTBLUESWORD_COLOR = 0x6699D8;
	public static int MAGENTASWORD_COLOR = 0xB24CD8;
	public static int ORANGESWORD_COLOR = 0xD87F33;
	public static int WHITESWORD_COLOR = 0xFFFFFF;
	public static int HARDSWORD_COLOR = 0x957D5A;

}
