package claymod.config;

import java.io.File;
import java.util.logging.Level;

import claymod.lib.ClayColors;
import claymod.lib.ClayStrings;
import claymod.main.ClayMod;
import cpw.mods.fml.common.FMLLog;
import net.minecraftforge.common.config.Configuration;

public class ConfigurationHandler {
	public static Configuration config;
	public static String CATEGORY_COLORS = "colors";
	
	public static void init(File file){
		config = new Configuration(file);
		ClayColors CC = new ClayColors();
		ClayStrings CS = new ClayStrings();
		
			config.load();
			
			CC.BLACKCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.BLACKCLAYSTICK_NAME, CC.BLACKCLAYSTICK_COLOR_DEFAULT).getInt(CC.BLACKCLAYSTICK_COLOR_DEFAULT);
			CC.REDCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.REDCLAYSTICK_NAME, CC.REDCLAYSTICK_COLOR_DEFAULT).getInt(CC.REDCLAYSTICK_COLOR_DEFAULT);
			CC.GREENCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.GREENCLAYSTICK_NAME, CC.GREENCLAYSTICK_COLOR_DEFAULT).getInt(CC.GREENCLAYSTICK_COLOR_DEFAULT);
			CC.BROWNCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.BROWNCLAYSTICK_NAME, CC.BROWNCLAYSTICK_COLOR_DEFAULT).getInt(CC.BROWNCLAYSTICK_COLOR_DEFAULT);
			CC.BLUECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.BLUECLAYSTICK_NAME, CC.BLUECLAYSTICK_COLOR_DEFAULT).getInt(CC.BLUECLAYSTICK_COLOR_DEFAULT);
			CC.PURPLECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.PURPLECLAYSTICK_NAME, CC.PURPLECLAYSTICK_COLOR_DEFAULT).getInt(CC.PURPLECLAYSTICK_COLOR_DEFAULT);
			CC.CYANCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.CYANCLAYSTICK_NAME, CC.CYANCLAYSTICK_COLOR_DEFAULT).getInt(CC.CYANCLAYSTICK_COLOR_DEFAULT);
			CC.LIGHTGRAYCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYCLAYSTICK_NAME, CC.LIGHTGRAYCLAYSTICK_COLOR_DEFAULT).getInt(CC.LIGHTGRAYCLAYSTICK_COLOR_DEFAULT);
			CC.GRAYCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.GRAYCLAYSTICK_NAME, CC.GRAYCLAYSTICK_COLOR_DEFAULT).getInt(CC.GRAYCLAYSTICK_COLOR_DEFAULT);
			CC.PINKCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.PINKCLAYSTICK_NAME, CC.PINKCLAYSTICK_COLOR_DEFAULT).getInt(CC.PINKCLAYSTICK_COLOR_DEFAULT);
			CC.LIMECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.LIMECLAYSTICK_NAME, CC.LIMECLAYSTICK_COLOR_DEFAULT).getInt(CC.LIMECLAYSTICK_COLOR_DEFAULT);
			CC.YELLOWCLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWCLAYSTICK_NAME, CC.YELLOWCLAYSTICK_COLOR_DEFAULT).getInt(CC.YELLOWCLAYSTICK_COLOR_DEFAULT);
			CC.LIGHTBLUECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUECLAYSTICK_NAME, CC.LIGHTBLUECLAYSTICK_COLOR_DEFAULT).getInt(CC.LIGHTBLUECLAYSTICK_COLOR_DEFAULT);
			CC.MAGENTACLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTACLAYSTICK_NAME, CC.MAGENTACLAYSTICK_COLOR_DEFAULT).getInt(CC.MAGENTACLAYSTICK_COLOR_DEFAULT);
			CC.ORANGECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.ORANGECLAYSTICK_NAME, CC.ORANGECLAYSTICK_COLOR_DEFAULT).getInt(CC.ORANGECLAYSTICK_COLOR_DEFAULT);
			CC.WHITECLAYSTICK_COLOR = config.get(CATEGORY_COLORS, CS.WHITECLAYSTICK_NAME, CC.WHITECLAYSTICK_COLOR_DEFAULT).getInt(CC.WHITECLAYSTICK_COLOR_DEFAULT);
			
			CC.BLACKPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.BLACKPICKAXE_NAME, CC.BLACKPICKAXE_COLOR_DEFAULT).getInt(CC.BLACKPICKAXE_COLOR_DEFAULT);
			CC.REDPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.REDPICKAXE_NAME, CC.REDPICKAXE_COLOR_DEFAULT).getInt(CC.REDPICKAXE_COLOR_DEFAULT);
			CC.GREENPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.GREENPICKAXE_NAME, CC.GREENPICKAXE_COLOR_DEFAULT).getInt(CC.GREENPICKAXE_COLOR_DEFAULT);
			CC.BROWNPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.BROWNPICKAXE_NAME, CC.BROWNPICKAXE_COLOR_DEFAULT).getInt(CC.BROWNPICKAXE_COLOR_DEFAULT);
			CC.BLUEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.BLUEPICKAXE_NAME, CC.BLUEPICKAXE_COLOR_DEFAULT).getInt(CC.BLUEPICKAXE_COLOR_DEFAULT);
			CC.PURPLEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.PURPLEPICKAXE_NAME, CC.PURPLEPICKAXE_COLOR_DEFAULT).getInt(CC.PURPLEPICKAXE_COLOR_DEFAULT);
			CC.CYANPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.CYANPICKAXE_NAME, CC.CYANPICKAXE_COLOR_DEFAULT).getInt(CC.CYANPICKAXE_COLOR_DEFAULT);
			CC.LIGHTGRAYPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYPICKAXE_NAME, CC.LIGHTGRAYPICKAXE_COLOR_DEFAULT).getInt(CC.LIGHTGRAYPICKAXE_COLOR_DEFAULT);
			CC.GRAYPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.GRAYPICKAXE_NAME, CC.GRAYPICKAXE_COLOR_DEFAULT).getInt(CC.GRAYPICKAXE_COLOR_DEFAULT);
			CC.PINKPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.PINKPICKAXE_NAME, CC.PINKPICKAXE_COLOR_DEFAULT).getInt(CC.PINKPICKAXE_COLOR_DEFAULT);
			CC.LIMEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIMEPICKAXE_NAME, CC.LIMEPICKAXE_COLOR_DEFAULT).getInt(CC.LIMEPICKAXE_COLOR_DEFAULT);
			CC.YELLOWPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWPICKAXE_NAME, CC.YELLOWPICKAXE_COLOR_DEFAULT).getInt(CC.YELLOWPICKAXE_COLOR_DEFAULT);
			CC.LIGHTBLUEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUEPICKAXE_NAME, CC.LIGHTBLUEPICKAXE_COLOR_DEFAULT).getInt(CC.LIGHTBLUEPICKAXE_COLOR_DEFAULT);
			CC.MAGENTAPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTAPICKAXE_NAME, CC.MAGENTAPICKAXE_COLOR_DEFAULT).getInt(CC.MAGENTAPICKAXE_COLOR_DEFAULT);
			CC.ORANGEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.ORANGEPICKAXE_NAME, CC.ORANGEPICKAXE_COLOR_DEFAULT).getInt(CC.ORANGEPICKAXE_COLOR_DEFAULT);
			CC.WHITEPICKAXE_COLOR = config.get(CATEGORY_COLORS, CS.WHITEPICKAXE_NAME, CC.WHITEPICKAXE_COLOR_DEFAULT).getInt(CC.WHITEPICKAXE_COLOR_DEFAULT);
			
			CC.BLACKAXE_COLOR = config.get(CATEGORY_COLORS, CS.BLACKAXE_NAME, CC.BLACKAXE_COLOR_DEFAULT).getInt(CC.BLACKAXE_COLOR_DEFAULT);
			CC.REDAXE_COLOR = config.get(CATEGORY_COLORS, CS.REDAXE_NAME, CC.REDAXE_COLOR_DEFAULT).getInt(CC.REDAXE_COLOR_DEFAULT);
			CC.GREENAXE_COLOR = config.get(CATEGORY_COLORS, CS.GREENAXE_NAME, CC.GREENAXE_COLOR_DEFAULT).getInt(CC.GREENAXE_COLOR_DEFAULT);
			CC.BROWNAXE_COLOR = config.get(CATEGORY_COLORS, CS.BROWNAXE_NAME, CC.BROWNAXE_COLOR_DEFAULT).getInt(CC.BROWNAXE_COLOR_DEFAULT);
			CC.BLUEAXE_COLOR = config.get(CATEGORY_COLORS, CS.BLUEAXE_NAME, CC.BLUEAXE_COLOR_DEFAULT).getInt(CC.BLUEAXE_COLOR_DEFAULT);
			CC.PURPLEAXE_COLOR = config.get(CATEGORY_COLORS, CS.PURPLEAXE_NAME, CC.PURPLEAXE_COLOR_DEFAULT).getInt(CC.PURPLEAXE_COLOR_DEFAULT);
			CC.CYANAXE_COLOR = config.get(CATEGORY_COLORS, CS.CYANAXE_NAME, CC.CYANAXE_COLOR_DEFAULT).getInt(CC.CYANAXE_COLOR_DEFAULT);
			CC.LIGHTGRAYAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYAXE_NAME, CC.LIGHTGRAYAXE_COLOR_DEFAULT).getInt(CC.LIGHTGRAYAXE_COLOR_DEFAULT);
			CC.GRAYAXE_COLOR = config.get(CATEGORY_COLORS, CS.GRAYAXE_NAME, CC.GRAYAXE_COLOR_DEFAULT).getInt(CC.GRAYAXE_COLOR_DEFAULT);
			CC.PINKAXE_COLOR = config.get(CATEGORY_COLORS, CS.PINKAXE_NAME, CC.PINKAXE_COLOR_DEFAULT).getInt(CC.PINKAXE_COLOR_DEFAULT);
			CC.LIMEAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIMEAXE_NAME, CC.LIMEAXE_COLOR_DEFAULT).getInt(CC.LIMEAXE_COLOR_DEFAULT);
			CC.YELLOWAXE_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWAXE_NAME, CC.YELLOWAXE_COLOR_DEFAULT).getInt(CC.YELLOWAXE_COLOR_DEFAULT);
			CC.LIGHTBLUEAXE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUEAXE_NAME, CC.LIGHTBLUEAXE_COLOR_DEFAULT).getInt(CC.LIGHTBLUEAXE_COLOR_DEFAULT);
			CC.MAGENTAAXE_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTAAXE_NAME, CC.MAGENTAAXE_COLOR_DEFAULT).getInt(CC.MAGENTAAXE_COLOR_DEFAULT);
			CC.ORANGEAXE_COLOR = config.get(CATEGORY_COLORS, CS.ORANGEAXE_NAME, CC.ORANGEAXE_COLOR_DEFAULT).getInt(CC.ORANGEAXE_COLOR_DEFAULT);
			CC.WHITEAXE_COLOR = config.get(CATEGORY_COLORS, CS.WHITEAXE_NAME, CC.WHITEAXE_COLOR_DEFAULT).getInt(CC.WHITEAXE_COLOR_DEFAULT);
			
			CC.BLACKHOE_COLOR = config.get(CATEGORY_COLORS, CS.BLACKHOE_NAME, CC.BLACKHOE_COLOR_DEFAULT).getInt(CC.BLACKHOE_COLOR_DEFAULT);
			CC.REDHOE_COLOR = config.get(CATEGORY_COLORS, CS.REDHOE_NAME, CC.REDHOE_COLOR_DEFAULT).getInt(CC.REDHOE_COLOR_DEFAULT);
			CC.GREENHOE_COLOR = config.get(CATEGORY_COLORS, CS.GREENHOE_NAME, CC.GREENHOE_COLOR_DEFAULT).getInt(CC.GREENHOE_COLOR_DEFAULT);
			CC.BROWNHOE_COLOR = config.get(CATEGORY_COLORS, CS.BROWNHOE_NAME, CC.BROWNHOE_COLOR_DEFAULT).getInt(CC.BROWNHOE_COLOR_DEFAULT);
			CC.BLUEHOE_COLOR = config.get(CATEGORY_COLORS, CS.BLUEHOE_NAME, CC.BLUEHOE_COLOR_DEFAULT).getInt(CC.BLUEHOE_COLOR_DEFAULT);
			CC.PURPLEHOE_COLOR = config.get(CATEGORY_COLORS, CS.PURPLEHOE_NAME, CC.PURPLEHOE_COLOR_DEFAULT).getInt(CC.PURPLEHOE_COLOR_DEFAULT);
			CC.CYANHOE_COLOR = config.get(CATEGORY_COLORS, CS.CYANHOE_NAME, CC.CYANHOE_COLOR_DEFAULT).getInt(CC.CYANHOE_COLOR_DEFAULT);
			CC.LIGHTGRAYHOE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYHOE_NAME, CC.LIGHTGRAYHOE_COLOR_DEFAULT).getInt(CC.LIGHTGRAYHOE_COLOR_DEFAULT);
			CC.GRAYHOE_COLOR = config.get(CATEGORY_COLORS, CS.GRAYHOE_NAME, CC.GRAYHOE_COLOR_DEFAULT).getInt(CC.GRAYHOE_COLOR_DEFAULT);
			CC.PINKHOE_COLOR = config.get(CATEGORY_COLORS, CS.PINKHOE_NAME, CC.PINKHOE_COLOR_DEFAULT).getInt(CC.PINKHOE_COLOR_DEFAULT);
			CC.LIMEHOE_COLOR = config.get(CATEGORY_COLORS, CS.LIMEHOE_NAME, CC.LIMEHOE_COLOR_DEFAULT).getInt(CC.LIMEHOE_COLOR_DEFAULT);
			CC.YELLOWHOE_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWHOE_NAME, CC.YELLOWHOE_COLOR_DEFAULT).getInt(CC.YELLOWHOE_COLOR_DEFAULT);
			CC.LIGHTBLUEHOE_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUEHOE_NAME, CC.LIGHTBLUEHOE_COLOR_DEFAULT).getInt(CC.LIGHTBLUEHOE_COLOR_DEFAULT);
			CC.MAGENTAHOE_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTAHOE_NAME, CC.MAGENTAHOE_COLOR_DEFAULT).getInt(CC.MAGENTAHOE_COLOR_DEFAULT);
			CC.ORANGEHOE_COLOR = config.get(CATEGORY_COLORS, CS.ORANGEHOE_NAME, CC.ORANGEHOE_COLOR_DEFAULT).getInt(CC.ORANGEHOE_COLOR_DEFAULT);
			CC.WHITEHOE_COLOR = config.get(CATEGORY_COLORS, CS.WHITEHOE_NAME, CC.WHITEHOE_COLOR_DEFAULT).getInt(CC.WHITEHOE_COLOR_DEFAULT);
			
			CC.BLACKSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.BLACKSHOVEL_NAME, CC.BLACKSHOVEL_COLOR_DEFAULT).getInt(CC.BLACKSHOVEL_COLOR_DEFAULT);
			CC.REDSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.REDSHOVEL_NAME, CC.REDSHOVEL_COLOR_DEFAULT).getInt(CC.REDSHOVEL_COLOR_DEFAULT);
			CC.GREENSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.GREENSHOVEL_NAME, CC.GREENSHOVEL_COLOR_DEFAULT).getInt(CC.GREENSHOVEL_COLOR_DEFAULT);
			CC.BROWNSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.BROWNSHOVEL_NAME, CC.BROWNSHOVEL_COLOR_DEFAULT).getInt(CC.BROWNSHOVEL_COLOR_DEFAULT);
			CC.BLUESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.BLUESHOVEL_NAME, CC.BLUESHOVEL_COLOR_DEFAULT).getInt(CC.BLUESHOVEL_COLOR_DEFAULT);
			CC.PURPLESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.PURPLESHOVEL_NAME, CC.PURPLESHOVEL_COLOR_DEFAULT).getInt(CC.PURPLESHOVEL_COLOR_DEFAULT);
			CC.CYANSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.CYANSHOVEL_NAME, CC.CYANSHOVEL_COLOR_DEFAULT).getInt(CC.CYANSHOVEL_COLOR_DEFAULT);
			CC.LIGHTGRAYSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYSHOVEL_NAME, CC.LIGHTGRAYSHOVEL_COLOR_DEFAULT).getInt(CC.LIGHTGRAYSHOVEL_COLOR_DEFAULT);
			CC.GRAYSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.GRAYSHOVEL_NAME, CC.GRAYSHOVEL_COLOR_DEFAULT).getInt(CC.GRAYSHOVEL_COLOR_DEFAULT);
			CC.PINKSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.PINKSHOVEL_NAME, CC.PINKSHOVEL_COLOR_DEFAULT).getInt(CC.PINKSHOVEL_COLOR_DEFAULT);
			CC.LIMESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.LIMESHOVEL_NAME, CC.LIMESHOVEL_COLOR_DEFAULT).getInt(CC.LIMESHOVEL_COLOR_DEFAULT);
			CC.YELLOWSHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWSHOVEL_NAME, CC.YELLOWSHOVEL_COLOR_DEFAULT).getInt(CC.YELLOWSHOVEL_COLOR_DEFAULT);
			CC.LIGHTBLUESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUESHOVEL_NAME, CC.LIGHTBLUESHOVEL_COLOR_DEFAULT).getInt(CC.LIGHTBLUESHOVEL_COLOR_DEFAULT);
			CC.MAGENTASHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTASHOVEL_NAME, CC.MAGENTASHOVEL_COLOR_DEFAULT).getInt(CC.MAGENTASHOVEL_COLOR_DEFAULT);
			CC.ORANGESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.ORANGESHOVEL_NAME, CC.ORANGESHOVEL_COLOR_DEFAULT).getInt(CC.ORANGESHOVEL_COLOR_DEFAULT);
			CC.WHITESHOVEL_COLOR = config.get(CATEGORY_COLORS, CS.WHITESHOVEL_NAME, CC.WHITESHOVEL_COLOR_DEFAULT).getInt(CC.WHITESHOVEL_COLOR_DEFAULT);
			
			CC.BLACKSWORD_COLOR = config.get(CATEGORY_COLORS, CS.BLACKSWORD_NAME, CC.BLACKSWORD_COLOR_DEFAULT).getInt(CC.BLACKSWORD_COLOR_DEFAULT);
			CC.REDSWORD_COLOR = config.get(CATEGORY_COLORS, CS.REDSWORD_NAME, CC.REDSWORD_COLOR_DEFAULT).getInt(CC.REDSWORD_COLOR_DEFAULT);
			CC.GREENSWORD_COLOR = config.get(CATEGORY_COLORS, CS.GREENSWORD_NAME, CC.GREENSWORD_COLOR_DEFAULT).getInt(CC.GREENSWORD_COLOR_DEFAULT);
			CC.BROWNSWORD_COLOR = config.get(CATEGORY_COLORS, CS.BROWNSWORD_NAME, CC.BROWNSWORD_COLOR_DEFAULT).getInt(CC.BROWNSWORD_COLOR_DEFAULT);
			CC.BLUESWORD_COLOR = config.get(CATEGORY_COLORS, CS.BLUESWORD_NAME, CC.BLUESWORD_COLOR_DEFAULT).getInt(CC.BLUESWORD_COLOR_DEFAULT);
			CC.PURPLESWORD_COLOR = config.get(CATEGORY_COLORS, CS.PURPLESWORD_NAME, CC.PURPLESWORD_COLOR_DEFAULT).getInt(CC.PURPLESWORD_COLOR_DEFAULT);
			CC.CYANSWORD_COLOR = config.get(CATEGORY_COLORS, CS.CYANSWORD_NAME, CC.CYANSWORD_COLOR_DEFAULT).getInt(CC.CYANSWORD_COLOR_DEFAULT);
			CC.LIGHTGRAYSWORD_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTGRAYSWORD_NAME, CC.LIGHTGRAYSWORD_COLOR_DEFAULT).getInt(CC.LIGHTGRAYSWORD_COLOR_DEFAULT);
			CC.GRAYSWORD_COLOR = config.get(CATEGORY_COLORS, CS.GRAYSWORD_NAME, CC.GRAYSWORD_COLOR_DEFAULT).getInt(CC.GRAYSWORD_COLOR_DEFAULT);
			CC.PINKSWORD_COLOR = config.get(CATEGORY_COLORS, CS.PINKSWORD_NAME, CC.PINKSWORD_COLOR_DEFAULT).getInt(CC.PINKSWORD_COLOR_DEFAULT);
			CC.LIMESWORD_COLOR = config.get(CATEGORY_COLORS, CS.LIMESWORD_NAME, CC.LIMESWORD_COLOR_DEFAULT).getInt(CC.LIMESWORD_COLOR_DEFAULT);
			CC.YELLOWSWORD_COLOR = config.get(CATEGORY_COLORS, CS.YELLOWSWORD_NAME, CC.YELLOWSWORD_COLOR_DEFAULT).getInt(CC.YELLOWSWORD_COLOR_DEFAULT);
			CC.LIGHTBLUESWORD_COLOR = config.get(CATEGORY_COLORS, CS.LIGHTBLUESWORD_NAME, CC.LIGHTBLUESWORD_COLOR_DEFAULT).getInt(CC.LIGHTBLUESWORD_COLOR_DEFAULT);
			CC.MAGENTASWORD_COLOR = config.get(CATEGORY_COLORS, CS.MAGENTASWORD_NAME, CC.MAGENTASWORD_COLOR_DEFAULT).getInt(CC.MAGENTASWORD_COLOR_DEFAULT);
			CC.ORANGESWORD_COLOR = config.get(CATEGORY_COLORS, CS.ORANGESWORD_NAME, CC.ORANGESWORD_COLOR_DEFAULT).getInt(CC.ORANGESWORD_COLOR_DEFAULT);
			CC.WHITESWORD_COLOR = config.get(CATEGORY_COLORS, CS.WHITESWORD_NAME, CC.WHITESWORD_COLOR_DEFAULT).getInt(CC.WHITESWORD_COLOR_DEFAULT);
			
			config.save();
		
		
	}
}
